spring:
  application:
    name: credit-services

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/mifos_credit_db
    username: postgres
    password: admin.2001


  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect


server:
  port: 9070
