spring:
  application:
    name: product

  datasource:
    driver-class-name: org.postgresql.Driver
z


  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8040
